services:
  db:
    container_name: ae-postgres
    image: postgres:13.1
    environment:
      POSTGRES_USER: applied_english_user
      POSTGRES_PASSWORD: ypc8y4wk725d
      POSTGRES_DB: applied_english
    ports:
      - "5432:5432"
    volumes:
      - ae-db-dev-data:/var/lib/postgresql/data
  db-test:
    container_name: ae-postgres-test
    image: postgres:13.1
    environment:
      POSTGRES_USER: applied_english_user
      POSTGRES_PASSWORD: ypc8a4wk725d
      POSTGRES_DB: applied_english_test
    ports:
      - "5434:5432"
  redis:
    container_name: ae-redis
    image: redis:6.0.10
    ports:
      - "6379:6379"
    volumes:
      - ae-redis-dev-data:/data
  pgadmin4:
    container_name: ae-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost
      PGADMIN_DEFAULT_PASSWORD: 2jfk6dw7e4f3
      PGADMIN_DISABLE_POSTFIX: 1
    ports:
      - "5433:80"
    volumes:
      - ae-pgadmin4-dev-data:/var/lib/pgadmin

volumes:
  ae-db-dev-data:
    name: ae-db-dev-data
  ae-redis-dev-data:
    name: ae-redis-dev-data
  ae-pgadmin4-dev-data:
    name: ae-pgadmin4-dev-data
